apiVersion: v1
kind: ConfigMap

metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: shipping

data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: shipping

spec:
  replicas: 1

  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: backend
      component: shipping

  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: backend
        component: shipping
    
    spec:
      containers:
      - name: shipping
        image: jayashankar1994/shipping:1.4.0
        imagePullPolicy: Always   # Kubernetes always checks the registry and pulls the image.
        resources:
          requests:
            cpu: "68m"
            memory: "100Mi"
          limits:
            cpu: "68m"
            memory: "100Mi"
        readinessProbe:
          # httpGet:
          #   path: /health
          #   port: 8080
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
          - configMapRef:
              name: shipping

---
apiVersion: v1
kind: Service

metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: shipping

spec:
  selector:
    project: roboshop
    environment: dev
    tier: backend
    component: shipping

  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping
  namespace: roboshop
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20