apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: db
    component: rabbitmq
spec:
  clusterIP: None
  selector:
    project: roboshop
    environment: dev
    tier: db
    component: rabbitmq

  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  serviceName: rabbitmq-headless
  replicas: 3
  
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: db
      component: rabbitmq

  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: db
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: jayashankar1994/rabbitmq:1.0.0
        volumeMounts:
        - name: rabbitmq
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: roboshop-ebs
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service

metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: db
    component: rabbitmq

spec:
  selector:
    project: roboshop
    environment: dev
    tier: db
    component: rabbitmq

  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017