apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: db
    component: mysql
spec:
  clusterIP: None
  selector:
    project: roboshop
    environment: dev
    tier: db
    component: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    project: roboshop
    environment: dev
    tier: db
    component: mysql
spec:
  serviceName: mysql-headless
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: db
      component: mysql
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: db
        component: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: roboshop-ebs
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: db
    component: mysql
spec:
  selector:
    project: roboshop
    environment: dev
    tier: db
    component: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306



