apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: db
    component: redis
spec:
  clusterIP: None
  selector:
    project: roboshop
    environment: dev
    tier: db
    component: redis

  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
spec:
  serviceName: redis-headless
  replicas: 3

  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: db
      component: redis

  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: db
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0
        volumeMounts:
        - name: redis
          mountPath: /data

  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: roboshop-ebs
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service

metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: db
    component: redis

spec:
  selector:
    project: roboshop
    environment: dev
    tier: db
    component: redis

  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379